Final Sprint 10
alex1056/java-filmorate pull request #2
Opened 2023-01-29 16:27 UTC by alex1056

Sprint 10

2023-01-30 08:36 UTC, ErkinKasymaliev requested changes
привет, хорошая работа!
оставил комменты

2023-01-30 08:36 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +class ErrorResponse {
уберите в отдельный класс

2023-01-30 08:36 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/CustomResponseExceptionController.java
> +//    @ExceptionHandler(ValidationException.class)
почему закомментили? за что отвечает этот класс?

2023-01-30 08:36 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private final List<Film> films = new ArrayList<>();
такс, давайте хранить в мапе

2023-01-30 17:21 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/controller/CustomResponseExceptionController.java
> +//    @ExceptionHandler(ValidationException.class)
Это лишний класс, убрал

2023-01-31 07:38 UTC, ErkinKasymaliev approved these changes
работа принята

2023-02-19 15:43 UTC, merged