Sprint 11, DB storage
alex1056/java-filmorate pull request #3
Opened 2023-02-19 15:37 UTC by alex1056

2023-02-20 17:22 UTC, ErkinKasymaliev requested changes
привет, отличная работа в плане Dao и service.
оставил пару комментов

2023-02-20 17:22 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +    private static final Logger log = LoggerFactory.getLogger(MpaController.class);
если использовать не будете - удалите

2023-02-20 17:22 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<?> addLike(@PathVariable Integer id, @PathVariable Integer userId) {
где то используете ResponseEntity, где то просто модель возвращаете. Приведите к одному стилю

2023-02-20 17:22 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        sql = "SELECT f.FILM_ID, f.NAME, f.DESCRIPTION, f.RELEASE_DATE, f.DURATION, f.MPA_ID, m.NAME\n" +
здесь можете вызвать getFilmById

2023-02-21 06:41 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        sql = "SELECT f.FILM_ID, f.NAME, f.DESCRIPTION, f.RELEASE_DATE, f.DURATION, f.MPA_ID, m.NAME\n" +
На предыдущем шаге фильм вставился в таблицу, но я не знаю его id, а чтобы проверить действительно ли фильм вставился (возвращаемое значение update дает количество измененных рядов, но мне это не надо, нужен сам фильм ) я делаю запрос и ищу по name и description тот самый фильм` sql = "SELECT f.FILM_ID, f.NAME, f.DESCRIPTION, f.RELEASE_DATE, f.DURATION, f.MPA_ID, m.NAME\n" +
                "FROM FILMS f  \n" +
                "LEFT JOIN MPA AS m ON m.MPA_ID = f.MPA_ID\n" +
                "WHERE f.name=? AND f.description=?";`

2023-02-22 07:38 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-02-22 07:38 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        sql = "SELECT f.FILM_ID, f.NAME, f.DESCRIPTION, f.RELEASE_DATE, f.DURATION, f.MPA_ID, m.NAME\n" +
это не правильно, вы можете вызвать из БД другой фильм (или очень похожий по названию и описанию, или у вас могут быть дубликаты). Лучше сделайте метод void.
 используйте 		KeyHolder keyHolder = new GeneratedKeyHolder();
чтобы получить id

2023-02-22 09:27 UTC, alex1056 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        sql = "SELECT f.FILM_ID, f.NAME, f.DESCRIPTION, f.RELEASE_DATE, f.DURATION, f.MPA_ID, m.NAME\n" +
Спасибо! Добавил, как раз этого не хватало для однозначности.

2023-02-22 11:34 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        return null;
лучше оставить как было

2023-02-22 11:34 UTC, ErkinKasymaliev approved these changes
работа принята

2023-02-23 07:52 UTC, merged